### ISSUE TITLE
properties.config.port seems to be ignored

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry-community/postgres-boshrelease#19]
I have a manifest that looks like this:

```
- name: postgresql
  jobs:
  - name: postgres
    release: postgres
    properties:
      config:
        port: 5432
      hba:
      - host all all 0.0.0.0/0 md5
      - host all all ::/0 md5
      replication:
        enabled: true
      users:
      - password: ...
        username: ...
```

But the postgresql.conf still has 6432 listed as the port, and that's what postgres is listening on.
