### ISSUE TITLE
pg_basebackup: could not connect to server: could not translate host name

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-community/postgres-boshrelease#2]
just tried your release
but i get this strange error

```
[repl:slave] DATADIR (/var/vcap/store/postgres/db) not found; seeding from preferred master ([172.21.42.167])
pg_basebackup: could not connect to server: could not translate host name "[172.21.42.167]" to address: Name or service not known
pg_ctl: directory "/var/vcap/store/postgres/db" does not exist
```

template i use http://pastebin.com/vv0n9Zxw

it fails on the first node (master)

```
  Started updating job postgres
  Started updating job postgres > postgres/0 (canary). Failed: `postgres/0' is not running after update (00:01:29)

Error 400007: `postgres/0' is not running after update
```

**Comment by jhunt** [comment]
The `postgres.replication.master` property needs to be a scalar, not a list.  Try changing this:

```
    properties:
      postgres:
        replication:
          master:
            - 172.21.42.167
```

to this:

```
    properties:
      postgres:
        replication:
          master: 172.21.42.167
```

The startup script is stringifying your array, which is where those weird square brackets come from in `could not translate host name "[172.21.42.167]"`

**Comment by ramonskie** [comment]
okay different error now..

```
[repl:slave] DATADIR (/var/vcap/store/postgres/db) not found; seeding from preferred master (172.21.42.167)
pg_basebackup: could not connect to server: could not connect to server: Connection refused
        Is the server running on host "172.21.42.167" and accepting
        TCP/IP connections on port 6432?
```

which is a bit of inception because postgres needs to be up and running before it can connects to itself

i also see the following in the monit/postgres log

```
ls: cannot access /var/vcap/packages/*/*/*.jar: No such file or directory
$PATH /var/vcap/packages/postgres/bin:/var/vcap/packages/pgpool2/bin:/bin:/usr/bin:/sbin:/usr/sbin
```

**Comment by jhunt** [comment]
Can you pastebin `/var/vcap/jobs/postgres/bin/ctl`?

**Comment by ramonskie** [comment]
http://pastebin.com/SJ6Ns47p

**Comment by jhunt** [comment]
Is your deployment multi-homed?

**Comment by ramonskie** [comment]
multi-homed?
i don't get what you mean

**Comment by jhunt** [comment]
You've got two networks on your postgres nodes:

```
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
          - 172.21.42.167
          - 172.21.42.170
          - 172.21.42.171
```

On postgres/0 (master), the interface attached to the `default` network is getting the IP `172.21.28.224`, which doesn't match the configured master IP, and causing the `bin/ctl` script to think that the node is actually a slave to `172.21.42.167`, causing the chicken/egg problem with seeding.

(Full disclosure, I haven't tested this on AWS yet, just vSphere and Warden CPIs)

Can you flip the order of the network definitions to this:

```
jobs:
  - name: postgres
    # ...
    networks:
      - name: floating
        static_ips:
          - 172.21.42.167
          - 172.21.42.170
          - 172.21.42.171
      - name: default
        default: [dns, gateway]
```
