### ISSUE TITLE
Error: Invalid CPI response - SchemaValidationError: Expected instance of Hash, given instance of NilClass

### ISSUE THREAD

**Issue by gherasima** [cloudfoundry-community/postgres-boshrelease#25]
Unable to deploy postgres-boshrelease
My IaaS is vShpere, using one ESXi 6.0

Task 687 | 18:22:23 | Preparing deployment: Preparing deployment (00:00:00)
Task 687 | 18:22:23 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 687 | 18:22:23 | Compiling packages: postgres/f72ef4e8dc8355070f22f8fe99a3e6a1e8355a9b
Task 687 | 18:22:23 | Compiling packages: pgrt/fdec5588f5c2c34039820660d73ae0055709f8bc
Task 687 | 18:22:24 | Compiling packages: postgres/f72ef4e8dc8355070f22f8fe99a3e6a1e8355a9b (00:00:01)
                    L Error: Invalid CPI response - SchemaValidationError: Expected instance of Hash, given instance of NilClass
Task 687 | 18:22:24 | Compiling packages: pgrt/fdec5588f5c2c34039820660d73ae0055709f8bc (00:00:01)
                    L Error: Invalid CPI response - SchemaValidationError: Expected instance of Hash, given instance of NilClass
Task 687 | 18:22:24 | Error: Invalid CPI response - SchemaValidationError: Expected instance of Hash, given instance of NilClass

Task 687 Started  Tue Jul 31 18:22:23 UTC 2018
Task 687 Finished Tue Jul 31 18:22:24 UTC 2018
Task 687 Duration 00:00:01
Task 687 error

Updating deployment:
  Expected task '687' to succeed but state is 'error'

Exit code 1

**Comment by jhunt** [comment]
What manifest are you deploying with?

**Comment by gherasima** [comment]
postgres-boshrelease/manifests/postgres.yml
```
---
name: postgres

instance_groups:
- azs:
  - z1
  name: postgres
  networks:
  - name: default
  persistent_disk_type: default
  stemcell: default
  vm_type: medium
  instances: 1
  jobs:
  - name: postgres
    properties:
      postgres:
        config:
          max_connections: 500
        databases:
        - extensions:
          - citext
          name: diegodb
          users:
          - hank
        - extensions:
          - citext
          name: uaadb
          users:
          - hank
        - extensions:
          - citext
          name: ccdb
          users:
          - hank
        hba:
        - host all all 0.0.0.0/0 md5
        - host all all ::/0 md5
        users:
        - admin: true
          password: propane
          username: hank
    release: postgres


- azs:
  - z1
  name: smoke-tests
  instances: 1
  lifecycle: errand
  networks:
  - name: default
  stemcell: default
  vm_type: small
  jobs:
  - name: smoke-tests
    properties:
      postgres:
        smoke-tests:
          backend:
            port: 6432
          target:
            port: 5432
            username: hank
            password: propane
    release: postgres

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-120000

releases:
- name: postgres
  version: 3.1.0
  url: https://github.com/cloudfoundry-community/postgres-boshrelease/releases/download/v3.1.0/postgres-3.1.0.tgz
  sha1: f90314b150279cfcf61b4e6842cbe29f1003898c
```
